# Baseline NLP — TF-IDF + LinearSVC

In [1]:
import pandas as pd

from sklearn.model_selection import train_test_split

from sklearn.feature_extraction.text import TfidfVectorizer

from sklearn.svm import LinearSVC

from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    accuracy_score,
    f1_score,
)

In [2]:
df = pd.read_csv("../data/processed/data_cleaned_v2md.csv")

df.head()

,user_id,tweet_id,tweet_text,class,tweet_text_len,tweet_text_clean
0,user0001,0d3ed29586ce,Cheesecake saludable sin azúcar y sin lactosa ...,control,77,cheesecake saludable sin azúcar y sin lactosa ...
1,user0002,c3cf897a495b,ser como ellas ♡♡\n #HastaLosHuesos,anorexia,35,ser como ellas ♡♡ hastaloshuesos
2,user0003,5041d85c45c6,"Comida Real o , la clave para estar más sana, ...",control,183,"comida real o , la clave para estar más sana, ..."
3,user0004,d18285d3c7ec,Entre el cambio de hora y la bajada de las #te...,control,217,entre el cambio de hora y la bajada de las tem...
4,user0005,4d81892f3217,Hace mucho tiempo no sentía mi cuerpo tan frío,anorexia,46,hace mucho tiempo no sentía mi cuerpo tan frío

In [3]:
print(df.columns.tolist())

['user_id', 'tweet_id', 'tweet_text', 'class', 'tweet_text_len', 'tweet_text_clean']

In [4]:
X = df["tweet_text_clean"]

Y = df["class"]

In [5]:
print(df["class"].value_counts())

print("\nDistribución porcentual:\n")

print(df["class"].value_counts(normalize=True))

class
anorexia    804
control     696
Name: count, dtype: int64

Distribución porcentual:

class
anorexia    0.536
control     0.464
Name: proportion, dtype: float64

In [6]:
df[["tweet_text_clean", "class"]].sample(20, random_state=42)

                                       tweet_text_clean     class
1116  "es el nuevo gurú de las top models, ¿sabes po...   control
1368         lo que necesitas para comenzar. motivación   control
422   festivo: día en el que puedes entrenar, irte a...   control
413           ¿que huesos te gustan más? proana thinspo  anorexia
451   inspiración princesas, no abandonéis :) ana mi...  anorexia
861   otro día más para entrenar duro y conseguir el...   control
1063  no es solo deporte, es un estilo de vida. salt...   control
741             a tomar mi te verde con canela y laurel  anorexia
1272  se puede vomitar en el colegio >.< pero es asq...  anorexia
259   buenos días y felizmartes . hoy toca luchar, p...   control
888   it's your lucky day . nosotros estaremos, para...   control
1432  hoy creo que estoy con más hambre que nunca, n...  anorexia
712   si puedo!! lo se no decaigo!! solo 6 kilos mas...  anorexia
1382  verga! ayer salí con mis amigas y trague como ...  anorexia
70              necesito vomitar todo lo que me comi :(  anorexia
1268  la mujer soñada. asi toda con todo en su lugar...   control
1491  con tu participación podemos seguir apoyando a...   control
607         publicidad y comida basura... narcolepticos   control
433       gym todo por llegar a la perfeccion misamigas  anorexia
51    hoy es el día internacional del café. y desde ...   control

In [51]:
X_train, X_test, y_train, Y_test = train_test_split(
    X,
    Y,
    test_size=0.2,
    random_state=42,
    stratify=Y
)

In [52]:
vectorizer = TfidfVectorizer(
    max_features=10000,
    ngram_range=(1,2),
    min_df=2
)

X_train_tfidf = vectorizer.fit_transform(X_train)

X_test_tfidf = vectorizer.transform(X_test)

In [53]:
print("Train shape:", X_train_tfidf.shape)

print("Test shape:", X_test_tfidf.shape)

Train shape: (1200, 3947)
Test shape: (300, 3947)

In [54]:
model = LinearSVC()

model.fit(X_train_tfidf, y_train)

LinearSVC()

In [55]:
y_pred = model.predict(X_test_tfidf)

In [56]:
accuracy = accuracy_score(Y_test, y_pred)

print("Accuracy:", accuracy)

Accuracy: 0.9033333333333333

In [57]:
f1 = f1_score(Y_test, y_pred, average="weighted")

print("F1-score:", f1)

F1-score: 0.9033948021136632

In [58]:
print(classification_report(Y_test, y_pred))

              precision    recall  f1-score   support

    anorexia       0.92      0.90      0.91       161
     control       0.89      0.91      0.90       139

    accuracy                           0.90       300
   macro avg       0.90      0.90      0.90       300
weighted avg       0.90      0.90      0.90       300

In [59]:
cm = confusion_matrix(Y_test, y_pred)

cm

array([[145,  16],
       [ 13, 126]])

In [60]:
results = pd.DataFrame({
    "text": X_test,
    "real": Y_test,
    "predicted": y_pred
})

results.sample(20, random_state=42)

                                                   text      real predicted
240   toma un trago de agua por cada bocado que le d...  anorexia  anorexia
775   ya llevo 20 horas de ayuno carreradekilos prin...  anorexia  anorexia
407   amputándome una pierna para poder alcanzar mi ...  anorexia  anorexia
359            una princesa que ríe quema más calorías.  anorexia  anorexia
1288  imagínate vos en seis meses con mucho ejercici...  anorexia  anorexia
1305  momento de escuchar música para relajarme y ol...  anorexia  anorexia
192          miren el cuerpito que tiene quiero. thispo  anorexia  anorexia
985    un rato en tu boca, para siempre en tus caderas.  anorexia   control
1043  día nueve de mi ayuno casi llega a su fin, que...  anorexia  anorexia
1425  nada mejor que correr 5km y haser unas series ...   control   control
224   dulces para la merienda, para la comida, para ...   control   control
695   quieren que haga algo al respecto, perfecto su...  anorexia  anorexia
104   parece que se aproximan mayores tasas de obesi...   control   control
1025         desde hoy , tomaré más agua que decisiones  anorexia  anorexia
549   el bacalao sí que es un superalimento y en nue...   control   control
187   incluye en tu alimentación diaria más frutas y...   control   control
27    me to others: everybody should love their body...  anorexia  anorexia
1134  mi secreto para vajar 15 kilos en un mes.ayuna...  anorexia  anorexia
1470  cerrando una semana más de preparación, se per...   control   control
663   buen día.a comer! así de completo en nutriente...   control   control

In [61]:
errors = results[results["real"] != results["predicted"]]

errors.sample(min(20, len(errors)), random_state=42)

                                                   text      real predicted
911   eso gracias por enviar a los deportistas al in...   control  anorexia
1135  sustituir marcas por las calorías. buena acció...   control  anorexia
289   hoy me regalo tiempo para aprender que no nece...  anorexia   control
28    tip esta lista es un resumen de la verduras y ...  anorexia   control
534   me alegro de que se tomen medidas contra algun...   control  anorexia
588   al gran problema de nadie le hace caso, esto e...  anorexia   control
964   mañana hablamos sobre la obsesión con la image...   control  anorexia
740   ¿por qué permitimos que estos mensajes circule...   control  anorexia
1199  ¿quieres adelgazar? aqui un truco. deja las id...   control  anorexia
288   ese asqueroso momento en el que te enteras de ...  anorexia   control
1309                 alaaa hace tiempo que no vomitaba!  anorexia   control
1440                      cena ay que obsesión con esto  anorexia   control
682   de verdad estáis a gusto con unos brazos y pie...  anorexia   control
338   me da asco esta sociedad en la que lo saludabl...  anorexia   control
975   yo me lo guiso, yo me lo como. integral casero...   control  anorexia
182   qué bonito sería despertar y tener el cuerpo q...  anorexia   control
4        hace mucho tiempo no sentía mi cuerpo tan frío  anorexia   control
1211  gordas que tienen cuentas en instagram y suben...  anorexia   control
353   me dais asco puro y duro los que enaltecéis el...  anorexia   control
196   por supuesto que el cielo existe lunesintratab...   control  anorexia